name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: web-ts/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: web-ts
    
    - name: Run TypeScript check
      run: npx tsc --noEmit
      working-directory: web-ts
    
    - name: Run tests
      run: npm test -- --watchAll=false
      working-directory: web-ts
    
    - name: Run linter
      run: npm run lint
      working-directory: web-ts
    
    - name: Build project
      run: npm run build
      working-directory: web-ts
      env:
        CI: true

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Deploy to Vercel
      run: |
        cd web-ts
        vercel --token ${VERCEL_TOKEN} --prod --confirm
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} 